version: '3'
services:
  mariadb:
    image: mariadb:10.8
    restart: always
    volumes:
      - ./volumes/mariadb:/var/lib/mysql:Z,rw
    environment:
      MARIADB_DATABASE:       "moodle"
      MARIADB_USER:           "moodle"
      MARIADB_PASSWORD:       "moodle"
      MARIADB_ROOT_PASSWORD:  "moodle"

  php:
    # this is the only piece we build
    # it holds the moodle folder and our plugins
    build: .
    image: webcursos.uai.cl/php:8.0-r1
    volumes:
      - ./volumes/moodle:/moodle:z,rw # moodle goes here
      - ./volumes/moodledata:/moodledata:z,rw

    # leave on 0:0 on podman
    # change to your UID on docker 
    # probably 1000:1000
    user: 1000:1000
    entrypoint: /entrypoint-php.sh
    environment:
      # the url used to access the server
      # http or https must be specified
      # the port must be the same one as nginx (the first one only)
      # if using port 80 (default) it must be omitted
      # if using https port must be omitted and https must be specified in url
      URL: http://vmlin77
      MODE: development # production or development
      MEMORY_LIMIT: 1G
      MAX_UPLOAD_SIZE: 1G
      MAX_EXECUTION_TIME: 600
    
  cron:
    # this uses a clone of the php container to run the cron
    image: webcursos.uai.cl/php:8.0-r1
    volumes:
      - ./volumes/moodle:/moodle:z,rw # moodle goes here
      - ./volumes/moodledata:/moodledata:z,rw
    environment:
      # the environment must have the same variables
      URL: http://vmlin77
      MODE: development
      MEMORY_LIMIT: 1G
      MAX_UPLOAD_SIZE: 1G
      MAX_EXECUTION_TIME: 600
    entrypoint: /entrypoint-cron.sh

  # supporting pieces
  redis:
    image: redis:7

  # node js in the future?

  # nginx exposes the server
  # it can be then reverse proxied further for SSL
  nginx:
    image: nginx:latest
    ports:
      - 80:80 # dont touch the second number, only the first one
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:Z,ro
      - ./volumes/moodle:/moodle:z,ro
      - ./volumes/moodledata:/moodledata:z,ro