version: '3'
services:
  mariadb:
    image: docker.io/library/mariadb:10.8
    restart: always
    network_mode: host
    volumes:
      - ./volumes/mariadb:/var/lib/mysql:Z,rw
    environment:
      MARIADB_DATABASE:       "moodle"
      MARIADB_USER:           "moodle"
      MARIADB_PASSWORD:       "moodle"
      MARIADB_ROOT_PASSWORD:  "moodle"

  redis:
    image: docker.io/library/redis:7
    restart: always
    network_mode: host

  php:
    # this is the only piece we build
    # it holds the moodle folder and our plugins
    build: .
    image: webcursos.uai.cl/php:8.0-r5
    restart: always
    network_mode: host
    depends_on:
      - mariadb
      - redis
    volumes:
      - ./volumes/moodle:/moodle:z,rw # moodle goes here
      - ./volumes/moodledata:/moodledata:z,rw
      - ./config/config.php:/moodle/config.php:Z,ro
    environment:
      URL: ${URL}
      PORT: ${PORT}
      MODE: ${MODE} 
      MEMORY_LIMIT: ${MEMORY_LIMIT}
      MAX_UPLOAD_SIZE: ${MAX_UPLOAD_SIZE}
      MAX_EXECUTION_TIME: ${MAX_EXECUTION_TIME}
      CRON_PASSWORD: ${CRON_PASSWORD}
      UID: ${UID}

  nginx:
    image: docker.io/library/nginx:1.23
    restart: always
    network_mode: host
    depends_on:
      - php
    volumes:
      - ./config/nginx.conf:/etc/nginx/templates/default.conf.template:Z,ro
      - ./volumes/moodle:/moodle:z,rw
      - ./volumes/moodledata:/moodledata:z,rw
    environment:
      URL: ${URL}
      PORT: ${PORT}
      MAX_UPLOAD_SIZE: ${MAX_UPLOAD_SIZE}
      MAX_EXECUTION_TIME: ${MAX_EXECUTION_TIME}

  webcron:
    image: docker.io/cw1900/docker-webcron:latest
    restart: always
    network_mode: host
    depends_on:
      - nginx
    environment:
      - INTERVAL_TIME=60
      # we can be lenient with the URL here since webcron can handle redirects just fine
      - URL=http://${URL}:${PORT}/admin/cron.php?password=${CRON_PASSWORD}