version: '3'
services:
  mariadb:
    image: docker.io/library/mariadb:10.8
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./volumes/mariadb:/var/lib/mysql:Z,rw
    environment:
      MARIADB_DATABASE:       "moodle"
      MARIADB_USER:           "moodle"
      MARIADB_PASSWORD:       "moodle"
      MARIADB_ROOT_PASSWORD:  "moodle"

  redis:
    image: docker.io/library/redis:7
    restart: always

  php:
    # this is the only piece we build
    # it holds the moodle folder and our plugins
    build: .
    image: webcursos.uai.cl/php:8.0-r4
    restart: always
    depends_on:
      - mariadb
      - redis
    volumes:
      - ./volumes/moodle:/moodle:z,rw # moodle goes here
      - ./volumes/moodledata:/moodledata:z,rw
      - ./config/config.php:/moodle/config.php:Z,ro
    environment:
      # the url used to access the server
      # http or https must be specified
      # trailing / must be omitted
      # the port must be the same one as nginx
      # if using port 80 (default) it must be omitted
      # if using https: port must be omitted and https must be specified in url
      URL: http://webcursos-d.uai.cl
      MODE: production # production or development
      MEMORY_LIMIT: 1G
      MAX_UPLOAD_SIZE: 1G
      MAX_EXECUTION_TIME: 600
      # the user id to run php under
      UID: 1000

  # nginx exposes the server
  # it can be then reverse proxied further for SSL
  nginx:
    image: docker.io/library/nginx:1.23
    restart: always
    depends_on:
      - php
    ports:
      # the port to expose the server on
      # change only first number (external port)
      - 80:80 
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:Z,ro
      - ./volumes/moodle:/moodle:z,rw
      - ./volumes/moodledata:/moodledata:z,rw

  webcron:
    image: docker.io/cw1900/docker-webcron:latest
    restart: always
    depends_on:
      - nginx
    environment:
      - INTERVAL_TIME=60
      # the url goes to nginx:80, this is then redirected to the actual url but its fine since this webcron can
      # handle it perfectly fine
      - URL=http://nginx:80/admin/cron.php?password=mBWPMCesiMwWFYu36Fa9zoWDRi8rDwWa3YKdnao6mCozZFUwLiNthVk54Fy7Ssu